### ISSUE TITLE
負荷テストTPとRabbitMQ serverとの接続が切れる

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/testau-chocolat#1]
event-hapi2-load-testブランチのd4c6bda59で、以下のようにeventを大量発生させると、RabbitMQ serverとの切断が発生する。

<pre>
$ ./events_generator.py 192.168.15.10 192.168.15.10   
Hatohol URL: http://192.168.15.10:33194
Try to login: hathol server: 192.168.15.10
Succeeded in login: API version: 4
Delete existing monitoring server: events-generator:0 (ID: 121)
Registered a monitoring server for event generation: events-generator:0 (ID: 122)
Generator: events-generator:0
Receiver: events-generator:0
Got response of exchange profile
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./events_generator.py", line 206, in __call__
    no_ack=True)
  File "/usr/lib/python2.7/dist-packages/pika/channel.py", line 221, in basic_consume
    {'consumer_tag': consumer_tag})])
  File "/usr/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1143, in _rpc
    self.connection.process_data_events()
  File "/usr/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 243, in process_data_events
    raise exceptions.ConnectionClosed()
ConnectionClosed
312.891 events/sec.
</pre>

なお、-sオプションをつけて、イベントを送信しないと、切断は発生しない。

<pre>
$ ./events_generator.py 192.168.15.10 192.168.15.10 -s
Hatohol URL: http://192.168.15.10:33194
Try to login: hathol server: 192.168.15.10
Succeeded in login: API version: 4
Delete existing monitoring server: events-generator:0 (ID: 124)
Registered a monitoring server for event generation: events-generator:0 (ID: 125)
Skip: Generater: events-generator:0
Receiver: events-generator:0
</pre>

ただし、問題が起こった直後の場合、-s付きでも切断することはある。
</pre>

**Comment by kz0817** [comment]
exchangeProfileの度にhatohol serverがqueueを再作成し、それによって切断されていると推測。

**Comment by kz0817** [comment]
```
Sep  9 08:48:20 chocolat-all-in-one hatohol[13582]: [INFO] <ArmBase.cc:320> ArmFake [148:events-generator:0]: requested to exit.
Sep  9 08:48:20 chocolat-all-in-one hatohol[13582]: [INFO] <ArmBase.cc:248> ArmFake [148:events-generator:0]: destruction: completed.
Sep  9 08:48:20 chocolat-all-in-one hatohol[13582]: [INFO] <AMQPConnection.cc:55> Broker URL: <amqp://192.168.15.10:5672/>
Sep  9 08:48:20 chocolat-all-in-one hatohol[13582]: [INFO] <AMQPConnection.cc:55> Broker URL: <amqp://192.168.15.10:5672/>
Sep  9 08:48:20 chocolat-all-in-one hatohol[13582]: [INFO] <AMQPConnection.cc:142> Queue: <events-generator.0-S>
Sep  9 08:48:20 chocolat-all-in-one hatohol[13582]: [INFO] <AMQPConnection.cc:142> Queue: <events-generator.0-T>
Sep  9 08:48:20 chocolat-all-in-one hatohol[13582]: [WARN] <HatoholArmPluginGateHAPI2.cc:449> The plugin control script isn't executable: /usr/libexec/hatohol/hap2/start-stop-hap2-zabbix-api.sh
Sep  9 08:48:20 chocolat-all-in-one hatohol[13582]: [INFO] <HatoholArmPluginGateHAPI2.cc:187> HAP Process connecting done. Connected HAP process name: "test event generator"
Sep  9 08:48:20 chocolat-all-in-one hatohol[13582]: [INFO] <AMQPConnection.cc:142> Queue: <events-generator.0-T>
Sep  9 08:48:20 chocolat-all-in-one hatohol[13582]: [INFO] <HatoholArmPluginGateHAPI2.cc:1604> Host cache: add-hoc registration. server: 149, hostIdInServer: 3
```

-T queueが２回作られてるから、上の推測は合ってると思う。

**Comment by kz0817** [comment]
あと、イベントをたくさん流したあと、-T queue (Hatohol server -> plugin)にデータがたくさん溜められている

<pre>
# rabbitmqctl list_queues
Listing queues ...
events-generator.0-S    0
events-generator.0-T    3472
</pre>

**Comment by kz0817** [comment]
これは、単に投げたEventの返事が返ってきてるだけだった。Receiverプロセスが死んでいるので、そえが溜まっているだけだった。

<pre>
$ amqp-get -u amqp://guest:guest@192.168.15.10 -q events-generator.0-T
{"jsonrpc":"2.0","result":"SUCCESS","id":490}
</pre>

**Comment by kz0817** [comment]
> exchangeProfileの度にhatohol serverがqueueを再作成し、それによって切断されていると推測。

いや、これは誤りの可能性が高い。Hatohol serverを停止した状態で、TPであるevents_generator.pyを実行しても、同じように例外が発生する。Hatohol serverを停止しても、queueは残り、その中のmessageもそのまま。

一度、TPを走らせると２０００ぐらい、Queueからメッセージがなくるが、TPで２〜３回データを取り出したところで、問題が発生する。pika内部の問題？

<pre>
# rabbitmqctl list_queues
Listing queues ...
events-generator.0-S    0
events-generator.0-T    181527
...done.
# rabbitmqctl list_queues
Listing queues ...
events-generator.0-S    0
events-generator.0-T    179177
</pre>

**Comment by ashie** [comment]
> > exchangeProfileの度にhatohol serverがqueueを再作成し、それによって切断されていると推測。
> > いや、これは誤りの可能性が高い。Hatohol serverを停止した状態で、TPであるevents_generator.pyを実行しても、同じように例外が発生する。

状況を理解できていないのですが、HatoholサーバはRabbitMQに再接続するときにqueueを
declareはしますが、能動的に消すことはしないです。
(queueのdeleteはユニットテストの中でしか行いません)

**Comment by kz0817** [comment]
例外発生ポイントまでのTraceback.

<pre>
(Pdb) (exctype, value, tb) = sys.exc_info()
(Pdb) traceback.print_exception(type, value, tb)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 240, in process_data_events
    if self._handle_read():
  File "/usr/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 348, in _handle_read
    super(BlockingConnection, self)._handle_read()
  File "/usr/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 351, in _handle_read
    self._on_data_available(data)
  File "/usr/lib/python2.7/dist-packages/pika/connection.py", line 1285, in _on_data_available
    self._process_frame(frame_value)
  File "/usr/lib/python2.7/dist-packages/pika/connection.py", line 1365, in _process_frame
    self._deliver_frame_to_channel(frame_value)
  File "/usr/lib/python2.7/dist-packages/pika/connection.py", line 976, in _deliver_frame_to_channel
    return self._channels[value.channel_number]._handle_content_frame(value)
  File "/usr/lib/python2.7/dist-packages/pika/channel.py", line 792, in _handle_content_frame
    self._on_deliver(*response)
  File "/usr/lib/python2.7/dist-packages/pika/channel.py", line 886, in _on_deliver
    body)
  File "./events_generator.py", line 215, in __consume_handler
    if self.__looks_like_exchange_profile(response):
  File "./events_generator.py", line 236, in __looks_like_exchange_profile
    if result.get("name") is None:
type: 'unicode' object has no attribute 'get'
</pre>

**Comment by kz0817** [comment]
「己の理性を疑え」、小柴さんの言葉らしい。

**Comment by kz0817** [comment]
結局、TPの受信コールバックハンドラの中で例外が発生していたのが原因。pikaライブラリのなかで、AttributeErrorがあれば、それをキャッチして、ConnectionClosedをraiseする処理があったので、根本原因がわかりにくくなっていた。
